### ISSUE TITLE
Route point <rtep> versus <rtept>

### ISSUE THREAD

**Issue by flap152** [Sibyx/phpGPX#21] opened 2017-12-20 22:38 UTC
I'm using Garmin Basecamp 4.6.2 and the route points are identified as `<rtept>` and not `<rtep>`
I made changes to the code and now export and import work with BaseCamp. Can someone explain this to me? Which format is correct?
EDIT: to clarify the "tone", I am new to GPX conversion and wondered how I could be the first one to report this on a seemingly basic feature, or whether Garmin was using non-standard syntax.

**Comment by Sibyx** [comment] 2017-12-21 11:26
Hi,
according to the [official specification](http://www.topografix.com/GPX/1/1/#type_rteType) the correct form is `rtept`. I made a typo in the library and I am using `rtep` instead. It's basically issue connected with Issue #20. I want to publish fix this week. I am apologise for the problems caused by my typo :(

**Comment by flap152** [comment] 2017-12-21 13:44
Thx for the quick response and confirmation. I am not confident enough to offer my fix as a pull request,  but I found it easy to trace and fix. I believe that shows quality in the code and it's structure. Glad to add this package to my "toolbox"

**Comment by Sibyx** [comment] 2018-01-15 22:17
Resolved in [RC-4](https://github.com/Sibyx/phpGPX/releases/tag/1.0-RC4)

**Closed by Sibyx** 2018-01-15 22:17 UTC
Labels: bug
