### ISSUE TITLE
RoutePoints and TripExtensions WIP

### ISSUE THREAD

**Issue by flap152** [Sibyx/phpGPX#22] opened 2017-12-23 12:48 UTC
I'm offering a patch file for work I did to:
1. Fix handling of rtept tag
2. Initial Implementation of the Garmin Trip Extension: parse and toXML, issue a ViaPoint or ShapingPoint extension tag as required
 
Notes on what I did and caveats:
- Duplicated the existing extension and modified to support http://www.garmin.com/xmlschemas/TripExtensions/v1
- Added rtept in Point model and PointParser
- Modified parsing to allow array of Points. Whitout my changes, only the first point in a route was parsed
- It seems Routes have rtept and tracks have rtep. I did not manage to handle both tags properly without issuing points twice in toXML: once for rtept, once for rtep. I comment out the undesired tag I want before running the code :-(

Hope this will be helpful and gets properly inserted in the code base. 

[rtept and Trip Extension WIP.zip](https://github.com/Sibyx/phpGPX/files/1584108/rtept.and.Trip.Extension.WIP.zip)

**Comment by Sibyx** [comment] 2017-12-27 11:14
Hi, thank you for the patch file. But I have problems applying to the project.

I have tried all these methods without success:

```bash
git apply --stat rtept.patch
```

or

```bash
patch -p1 < rtept.patch 
```

I always have the same result: `unrecognized input`

I have no idea where is the problem... If you want we can create a new upstream branch and you can create a new PR or please re-upload the patch file.

**Comment by Sibyx** [comment] 2018-01-15 22:18
As I said I was unable to use your patch so I made my own solution. The issue is resolved with [RC-4](https://github.com/Sibyx/phpGPX/releases/tag/1.0-RC4).

**Closed by Sibyx** 2018-01-15 22:18 UTC
